### PR TITLE
21: Updates types and fixes whitespace

### LINKED ISSUE #21: SDK: update types to use siwf types
## Problem:
- Currently we're crating local types because siwf/gateway currently only supports SR25519

## Solution:
For those that are applicable:
- remove custom types
- import types from `@projectlibertylabs/siwf` as to create a single source of truth

### PR DESCRIPTION
**Pull request by julian-amplica**
Closes #21 

I also noticed there was some whitespace in the CAIP template so I tried to fix that—there's probably a better way to do multiline strings without having right justify but I don't know what it is off the top of my head

### CODE REVIEW

File: src/helpers/siwf.ts [hunk 1]
```diff
@@ -1,25 +1,30 @@
...
   const loginCaip122 = `${payloadArguments.domain} wants you to sign in with your Frequency account:
-    frequency:${payloadArguments.chainId}:${userAddress}
-    
-    URI: ${payloadArguments.uri}
-    Version: ${payloadArguments.version}
-    Nonce: ${payloadArguments.nonce}
-    Chain ID: frequency:${payloadArguments.chainId}
-    Issued At: ${payloadArguments.issuedAt}
-  `;
+frequency:${payloadArguments.chainId}:${userAddress}
```
Comment (claireclark1) [inline src/helpers/siwf.ts:21]: can you please run `format` just to double check this spacing is correct

**Review by claireclark1 — APPROVED** [review]
Looks so good!!

File: src/helpers/siwf.ts (hunk 1 above)
Comment (julian-amplica) [reply src/helpers/siwf.ts:21]: The spacing is 'correct' but ugly—the CAIP 122 spec doesn't include whitespace on the left side so we need to match that unfortunately. There's probably a better way; I'll circle back to this
